### ISSUE TITLE
Proposal: Update staking rewards to include Uniswap liquidity providers.

### ISSUE THREAD

**Issue by jmacwhyte** [vybetoken/vybe#11]
Vybe uses vybe tokens to provide services. In the case of flash loans, users can borrow a large amount of vybe tokens and perform arbitrage trades between multiple DEXes before returning the tokens. Other upcoming services will presumably also include interfacing with other smart contracts and/or tokens outside of the Vybe ecosystem.

Vybe token holders stake their tokens to make them available to the Vybe smart contracts, which offer the above-mentioned services on behalf of the user and pay a reward. However, in order for these services to function, the tokens also need to be easily converted to other tokens or assets for use outside of the Vybe contracts.

The current staking rewards scheme pays rewards to users who stake with the Vybe contract but not to anyone else. This incentivizes holders to stake their tokens in the Vybe smart contracts instead of using them to provide trading liquidity on Uniswap or other DEXs, for fear of missing out on staking rewards. This leads to insufficient trading liquidity for the Vybe services to function.

I propose the staking scheme be updated to award 50% of new rewards to users who stake tokens with the Vybe smart contract, as it works now, and to award the other 50% of new rewards to users who have added their Vybe tokens to the Uniswap Vybe-ETH liquidity pool. 

Each half of the rewards would be distributed proportionally amongst the eligible token stakers in each pool, meaning if the Uniswap liquidity pool has less tokens staked than the Vybe smart contract, new stakers would get a bigger return by adding their tokens to Uniswap, as they would constitute a larger share of that pool. In this way market mechanics would work to ensure both liquidity pools are roughly equal in size.

As for implementation: the current setup looks at a user's staked Vybe balance compared to the total staked balance to calculate how many rewards the user should receive. Under this proposal, it should instead issue 50% of total rewards in the existing way, and for the remaining 50% of the rewards it should look at the user's balance of Uniswap liquidity tokens (held in the Uniswap smart contract) compared to the total number of liquidity tokens issued.

**Comment by schenkty** [comment]
Thank you, @jmacwhyte, for submitting this proposal. After discussing with @bighandsdev, we will include staking rewards for liquidity providers as part of the staking contract upgrades. 

@bighandsdev, Let's implement a two percent staking reward for any stakeholder who opts to become a liquidity provider. The new staking reward should be in addition to the stakeholder's current staking rate. Liquidity provided via the staking contract will then be provided directly to the Uniswap contract.

**Comment by schenkty** [comment]
Going to close this as we have addressed it in our Staking 2.0 proposal.
