### ISSUE TITLE
Vybe Loyalty modifier token

### ISSUE THREAD

**Issue by schenkty** [vybetoken/vybe#9]
As we move towards a loyalty program, let's simply our modifier tracking and issue loyalty modifier tokens. These tokens are similar to [NFTs](https://en.wikipedia.org/wiki/Non-fungible_token) which allow Vybe holders to collect modifiers and spend them when they choose to. 

We should create three unique modifier tokens, one to represent each loyalty tier listed below. 
- Silver
- Gold
- Platinum

Modifier tokens should be issued at the end of each relative staking month under the following guidelines:
- If this is the stake holders first or second month, issue one Silver token.
- If this is the stake holders third, fourth, or fifth month, issue one Gold token.
- If this is the stake holder has staked Vybe for 6 months or longer, issue one Platinum token.

**Comment by bighandsdev** [comment]
NFTs have been added to the contract with the specifications outlined
